controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

main:
    path:       /
    controller: App\Controller\HomeController::index
app_register:
    path:       /register32983792873987982739827398273982
    controller: App\Controller\SecurityController::register
app_login:
    path:       /amxlogin
    controller: App\Controller\SecurityController::login
module:
    path:       /module
    controller: App\Controller\StaticController::module
startover:
    path:       /startover
    controller: App\Controller\StaticController::startover
partner:
    path:       /partner
    controller: App\Controller\StaticController::partner
secondaire:
    path:       /secondaire
    controller: App\Controller\StaticController::secondaire
superieur:
    path:       /superieur
    controller: App\Controller\StaticController::superieur
contact:
    path:       /contact
    controller: App\Controller\StaticController::contact
calendar:
    path:       /calendar
    controller: App\Controller\StaticController::calendar
managerstu:
    path:       /managerstu
    controller: App\Controller\AdminSTUController::managerstu